//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSInfoserviceCustomer1.WSInfoservice {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://infoservice.webservice.as24.com/")]
    public partial class TechnicalFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeErrorField;
        
        private string messageErrorField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string codeError {
            get {
                return this.codeErrorField;
            }
            set {
                this.codeErrorField = value;
                this.RaisePropertyChanged("codeError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string messageError {
            get {
                return this.messageErrorField;
            }
            set {
                this.messageErrorField = value;
                this.RaisePropertyChanged("messageError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://infoservice.webservice.as24.com/")]
    public partial class transaction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string offerTypeField;
        
        private string providerCodeField;
        
        private string transactionNumberField;
        
        private string documentNumberField;
        
        private System.DateTime documentDateField;
        
        private bool documentDateFieldSpecified;
        
        private System.DateTime documentMaturityDateField;
        
        private bool documentMaturityDateFieldSpecified;
        
        private string clientIdField;
        
        private string vCNumberField;
        
        private string vCDuplicateNumberField;
        
        private string vCTypeField;
        
        private string vCRegistrationNumberField;
        
        private string vCVehicleTypeField;
        
        private string vCDriverNameField;
        
        private string vCCMVField;
        
        private System.DateTime vCExpiryDateField;
        
        private bool vCExpiryDateFieldSpecified;
        
        private string dCNumberField;
        
        private string dCDuplicateNumberField;
        
        private string dCTypeField;
        
        private string dCRegistrationNumberField;
        
        private string dCVehicleTypeField;
        
        private string dCDriverNameField;
        
        private string dCCMVField;
        
        private System.DateTime dCExpiryDateField;
        
        private bool dCExpiryDateFieldSpecified;
        
        private string referenceTakField;
        
        private string equipmentCodeField;
        
        private string equipmentProviderCodeField;
        
        private string entryPartnerCodeField;
        
        private string entryISOCodeField;
        
        private string entryIdNumberField;
        
        private string entryMotorwayCodeField;
        
        private string cIMField;
        
        private string entryPlaceNameField;
        
        private string entryCurrencyCodeField;
        
        private string entryPlacePostalCodeField;
        
        private string entryRegionCodeField;
        
        private System.DateTime entryTransactionDateField;
        
        private bool entryTransactionDateFieldSpecified;
        
        private string exitPartnerCodeField;
        
        private string exitISOCodeField;
        
        private string exitIdNumberField;
        
        private string exitMotorwayCodeField;
        
        private string exitPlaceNameField;
        
        private string exitCurrencyCodeField;
        
        private string exitPlacePostalCodeField;
        
        private string exitRegionCodeField;
        
        private System.DateTime exitTransactionDateField;
        
        private bool exitTransactionDateFieldSpecified;
        
        private string transactionTypeField;
        
        private string transactionSignField;
        
        private string recoveryNumberField;
        
        private string productCodeField;
        
        private string productDesignationField;
        
        private double quantityField;
        
        private double mileageField;
        
        private System.DateTime transactionValueDateField;
        
        private bool transactionValueDateFieldSpecified;
        
        private double priceListVATInclField;
        
        private double unitPriceVATInclField;
        
        private double unitDiscountVATInclField;
        
        private double unitPriceVATExclField;
        
        private double unitVATRateField;
        
        private string discountCodeField;
        
        private string transactionInformationField;
        
        private string observationCodeField;
        
        private string finalClassField;
        
        private double totalPriceVATExclField;
        
        private double totalVATRateField;
        
        private double totalPriceVATInclField;
        
        private string paymentCurrencyCodeField;
        
        private double paymentVATExclField;
        
        private double paymentVATRateField;
        
        private double paymentVATInclField;
        
        private string matchingTransactionField;
        
        private string euroclassField;
        
        private string partnerNameField;
        
        private bool isInvoicedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string offerType {
            get {
                return this.offerTypeField;
            }
            set {
                this.offerTypeField = value;
                this.RaisePropertyChanged("offerType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string providerCode {
            get {
                return this.providerCodeField;
            }
            set {
                this.providerCodeField = value;
                this.RaisePropertyChanged("providerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string transactionNumber {
            get {
                return this.transactionNumberField;
            }
            set {
                this.transactionNumberField = value;
                this.RaisePropertyChanged("transactionNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string documentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
                this.RaisePropertyChanged("documentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime documentDate {
            get {
                return this.documentDateField;
            }
            set {
                this.documentDateField = value;
                this.RaisePropertyChanged("documentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool documentDateSpecified {
            get {
                return this.documentDateFieldSpecified;
            }
            set {
                this.documentDateFieldSpecified = value;
                this.RaisePropertyChanged("documentDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime documentMaturityDate {
            get {
                return this.documentMaturityDateField;
            }
            set {
                this.documentMaturityDateField = value;
                this.RaisePropertyChanged("documentMaturityDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool documentMaturityDateSpecified {
            get {
                return this.documentMaturityDateFieldSpecified;
            }
            set {
                this.documentMaturityDateFieldSpecified = value;
                this.RaisePropertyChanged("documentMaturityDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string clientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
                this.RaisePropertyChanged("clientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string VCNumber {
            get {
                return this.vCNumberField;
            }
            set {
                this.vCNumberField = value;
                this.RaisePropertyChanged("VCNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string VCDuplicateNumber {
            get {
                return this.vCDuplicateNumberField;
            }
            set {
                this.vCDuplicateNumberField = value;
                this.RaisePropertyChanged("VCDuplicateNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string VCType {
            get {
                return this.vCTypeField;
            }
            set {
                this.vCTypeField = value;
                this.RaisePropertyChanged("VCType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string VCRegistrationNumber {
            get {
                return this.vCRegistrationNumberField;
            }
            set {
                this.vCRegistrationNumberField = value;
                this.RaisePropertyChanged("VCRegistrationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string VCVehicleType {
            get {
                return this.vCVehicleTypeField;
            }
            set {
                this.vCVehicleTypeField = value;
                this.RaisePropertyChanged("VCVehicleType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string VCDriverName {
            get {
                return this.vCDriverNameField;
            }
            set {
                this.vCDriverNameField = value;
                this.RaisePropertyChanged("VCDriverName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string VCCMV {
            get {
                return this.vCCMVField;
            }
            set {
                this.vCCMVField = value;
                this.RaisePropertyChanged("VCCMV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public System.DateTime VCExpiryDate {
            get {
                return this.vCExpiryDateField;
            }
            set {
                this.vCExpiryDateField = value;
                this.RaisePropertyChanged("VCExpiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VCExpiryDateSpecified {
            get {
                return this.vCExpiryDateFieldSpecified;
            }
            set {
                this.vCExpiryDateFieldSpecified = value;
                this.RaisePropertyChanged("VCExpiryDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string DCNumber {
            get {
                return this.dCNumberField;
            }
            set {
                this.dCNumberField = value;
                this.RaisePropertyChanged("DCNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string DCDuplicateNumber {
            get {
                return this.dCDuplicateNumberField;
            }
            set {
                this.dCDuplicateNumberField = value;
                this.RaisePropertyChanged("DCDuplicateNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string DCType {
            get {
                return this.dCTypeField;
            }
            set {
                this.dCTypeField = value;
                this.RaisePropertyChanged("DCType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string DCRegistrationNumber {
            get {
                return this.dCRegistrationNumberField;
            }
            set {
                this.dCRegistrationNumberField = value;
                this.RaisePropertyChanged("DCRegistrationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string DCVehicleType {
            get {
                return this.dCVehicleTypeField;
            }
            set {
                this.dCVehicleTypeField = value;
                this.RaisePropertyChanged("DCVehicleType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string DCDriverName {
            get {
                return this.dCDriverNameField;
            }
            set {
                this.dCDriverNameField = value;
                this.RaisePropertyChanged("DCDriverName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string DCCMV {
            get {
                return this.dCCMVField;
            }
            set {
                this.dCCMVField = value;
                this.RaisePropertyChanged("DCCMV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public System.DateTime DCExpiryDate {
            get {
                return this.dCExpiryDateField;
            }
            set {
                this.dCExpiryDateField = value;
                this.RaisePropertyChanged("DCExpiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DCExpiryDateSpecified {
            get {
                return this.dCExpiryDateFieldSpecified;
            }
            set {
                this.dCExpiryDateFieldSpecified = value;
                this.RaisePropertyChanged("DCExpiryDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string referenceTak {
            get {
                return this.referenceTakField;
            }
            set {
                this.referenceTakField = value;
                this.RaisePropertyChanged("referenceTak");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string equipmentCode {
            get {
                return this.equipmentCodeField;
            }
            set {
                this.equipmentCodeField = value;
                this.RaisePropertyChanged("equipmentCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string equipmentProviderCode {
            get {
                return this.equipmentProviderCodeField;
            }
            set {
                this.equipmentProviderCodeField = value;
                this.RaisePropertyChanged("equipmentProviderCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string entryPartnerCode {
            get {
                return this.entryPartnerCodeField;
            }
            set {
                this.entryPartnerCodeField = value;
                this.RaisePropertyChanged("entryPartnerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string entryISOCode {
            get {
                return this.entryISOCodeField;
            }
            set {
                this.entryISOCodeField = value;
                this.RaisePropertyChanged("entryISOCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string entryIdNumber {
            get {
                return this.entryIdNumberField;
            }
            set {
                this.entryIdNumberField = value;
                this.RaisePropertyChanged("entryIdNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string entryMotorwayCode {
            get {
                return this.entryMotorwayCodeField;
            }
            set {
                this.entryMotorwayCodeField = value;
                this.RaisePropertyChanged("entryMotorwayCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string CIM {
            get {
                return this.cIMField;
            }
            set {
                this.cIMField = value;
                this.RaisePropertyChanged("CIM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string entryPlaceName {
            get {
                return this.entryPlaceNameField;
            }
            set {
                this.entryPlaceNameField = value;
                this.RaisePropertyChanged("entryPlaceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string entryCurrencyCode {
            get {
                return this.entryCurrencyCodeField;
            }
            set {
                this.entryCurrencyCodeField = value;
                this.RaisePropertyChanged("entryCurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string entryPlacePostalCode {
            get {
                return this.entryPlacePostalCodeField;
            }
            set {
                this.entryPlacePostalCodeField = value;
                this.RaisePropertyChanged("entryPlacePostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string entryRegionCode {
            get {
                return this.entryRegionCodeField;
            }
            set {
                this.entryRegionCodeField = value;
                this.RaisePropertyChanged("entryRegionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public System.DateTime entryTransactionDate {
            get {
                return this.entryTransactionDateField;
            }
            set {
                this.entryTransactionDateField = value;
                this.RaisePropertyChanged("entryTransactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool entryTransactionDateSpecified {
            get {
                return this.entryTransactionDateFieldSpecified;
            }
            set {
                this.entryTransactionDateFieldSpecified = value;
                this.RaisePropertyChanged("entryTransactionDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string exitPartnerCode {
            get {
                return this.exitPartnerCodeField;
            }
            set {
                this.exitPartnerCodeField = value;
                this.RaisePropertyChanged("exitPartnerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string exitISOCode {
            get {
                return this.exitISOCodeField;
            }
            set {
                this.exitISOCodeField = value;
                this.RaisePropertyChanged("exitISOCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string exitIdNumber {
            get {
                return this.exitIdNumberField;
            }
            set {
                this.exitIdNumberField = value;
                this.RaisePropertyChanged("exitIdNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string exitMotorwayCode {
            get {
                return this.exitMotorwayCodeField;
            }
            set {
                this.exitMotorwayCodeField = value;
                this.RaisePropertyChanged("exitMotorwayCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string exitPlaceName {
            get {
                return this.exitPlaceNameField;
            }
            set {
                this.exitPlaceNameField = value;
                this.RaisePropertyChanged("exitPlaceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string exitCurrencyCode {
            get {
                return this.exitCurrencyCodeField;
            }
            set {
                this.exitCurrencyCodeField = value;
                this.RaisePropertyChanged("exitCurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string exitPlacePostalCode {
            get {
                return this.exitPlacePostalCodeField;
            }
            set {
                this.exitPlacePostalCodeField = value;
                this.RaisePropertyChanged("exitPlacePostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string exitRegionCode {
            get {
                return this.exitRegionCodeField;
            }
            set {
                this.exitRegionCodeField = value;
                this.RaisePropertyChanged("exitRegionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public System.DateTime exitTransactionDate {
            get {
                return this.exitTransactionDateField;
            }
            set {
                this.exitTransactionDateField = value;
                this.RaisePropertyChanged("exitTransactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool exitTransactionDateSpecified {
            get {
                return this.exitTransactionDateFieldSpecified;
            }
            set {
                this.exitTransactionDateFieldSpecified = value;
                this.RaisePropertyChanged("exitTransactionDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string transactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
                this.RaisePropertyChanged("transactionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string transactionSign {
            get {
                return this.transactionSignField;
            }
            set {
                this.transactionSignField = value;
                this.RaisePropertyChanged("transactionSign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string recoveryNumber {
            get {
                return this.recoveryNumberField;
            }
            set {
                this.recoveryNumberField = value;
                this.RaisePropertyChanged("recoveryNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string productCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("productCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=49)]
        public string productDesignation {
            get {
                return this.productDesignationField;
            }
            set {
                this.productDesignationField = value;
                this.RaisePropertyChanged("productDesignation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=50)]
        public double quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=51)]
        public double mileage {
            get {
                return this.mileageField;
            }
            set {
                this.mileageField = value;
                this.RaisePropertyChanged("mileage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=52)]
        public System.DateTime transactionValueDate {
            get {
                return this.transactionValueDateField;
            }
            set {
                this.transactionValueDateField = value;
                this.RaisePropertyChanged("transactionValueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionValueDateSpecified {
            get {
                return this.transactionValueDateFieldSpecified;
            }
            set {
                this.transactionValueDateFieldSpecified = value;
                this.RaisePropertyChanged("transactionValueDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=53)]
        public double priceListVATIncl {
            get {
                return this.priceListVATInclField;
            }
            set {
                this.priceListVATInclField = value;
                this.RaisePropertyChanged("priceListVATIncl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=54)]
        public double unitPriceVATIncl {
            get {
                return this.unitPriceVATInclField;
            }
            set {
                this.unitPriceVATInclField = value;
                this.RaisePropertyChanged("unitPriceVATIncl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=55)]
        public double unitDiscountVATIncl {
            get {
                return this.unitDiscountVATInclField;
            }
            set {
                this.unitDiscountVATInclField = value;
                this.RaisePropertyChanged("unitDiscountVATIncl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=56)]
        public double unitPriceVATExcl {
            get {
                return this.unitPriceVATExclField;
            }
            set {
                this.unitPriceVATExclField = value;
                this.RaisePropertyChanged("unitPriceVATExcl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=57)]
        public double unitVATRate {
            get {
                return this.unitVATRateField;
            }
            set {
                this.unitVATRateField = value;
                this.RaisePropertyChanged("unitVATRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=58)]
        public string discountCode {
            get {
                return this.discountCodeField;
            }
            set {
                this.discountCodeField = value;
                this.RaisePropertyChanged("discountCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=59)]
        public string transactionInformation {
            get {
                return this.transactionInformationField;
            }
            set {
                this.transactionInformationField = value;
                this.RaisePropertyChanged("transactionInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=60)]
        public string observationCode {
            get {
                return this.observationCodeField;
            }
            set {
                this.observationCodeField = value;
                this.RaisePropertyChanged("observationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=61)]
        public string finalClass {
            get {
                return this.finalClassField;
            }
            set {
                this.finalClassField = value;
                this.RaisePropertyChanged("finalClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=62)]
        public double totalPriceVATExcl {
            get {
                return this.totalPriceVATExclField;
            }
            set {
                this.totalPriceVATExclField = value;
                this.RaisePropertyChanged("totalPriceVATExcl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=63)]
        public double totalVATRate {
            get {
                return this.totalVATRateField;
            }
            set {
                this.totalVATRateField = value;
                this.RaisePropertyChanged("totalVATRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=64)]
        public double totalPriceVATIncl {
            get {
                return this.totalPriceVATInclField;
            }
            set {
                this.totalPriceVATInclField = value;
                this.RaisePropertyChanged("totalPriceVATIncl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=65)]
        public string paymentCurrencyCode {
            get {
                return this.paymentCurrencyCodeField;
            }
            set {
                this.paymentCurrencyCodeField = value;
                this.RaisePropertyChanged("paymentCurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=66)]
        public double paymentVATExcl {
            get {
                return this.paymentVATExclField;
            }
            set {
                this.paymentVATExclField = value;
                this.RaisePropertyChanged("paymentVATExcl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=67)]
        public double paymentVATRate {
            get {
                return this.paymentVATRateField;
            }
            set {
                this.paymentVATRateField = value;
                this.RaisePropertyChanged("paymentVATRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=68)]
        public double paymentVATIncl {
            get {
                return this.paymentVATInclField;
            }
            set {
                this.paymentVATInclField = value;
                this.RaisePropertyChanged("paymentVATIncl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=69)]
        public string matchingTransaction {
            get {
                return this.matchingTransactionField;
            }
            set {
                this.matchingTransactionField = value;
                this.RaisePropertyChanged("matchingTransaction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=70)]
        public string euroclass {
            get {
                return this.euroclassField;
            }
            set {
                this.euroclassField = value;
                this.RaisePropertyChanged("euroclass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=71)]
        public string partnerName {
            get {
                return this.partnerNameField;
            }
            set {
                this.partnerNameField = value;
                this.RaisePropertyChanged("partnerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=72)]
        public bool isInvoiced {
            get {
                return this.isInvoicedField;
            }
            set {
                this.isInvoicedField = value;
                this.RaisePropertyChanged("isInvoiced");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://infoservice.webservice.as24.com/", ConfigurationName="WSInfoservice.InfoService")]
    public interface InfoService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WSInfoserviceCustomer1.WSInfoservice.TechnicalFault), Action="", Name="TechnicalFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSInfoserviceCustomer1.WSInfoservice.getInvoicingTransactionsResponse getInvoicingTransactions(WSInfoserviceCustomer1.WSInfoservice.getInvoicingTransactions request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WSInfoserviceCustomer1.WSInfoservice.TechnicalFault), Action="", Name="TechnicalFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSInfoserviceCustomer1.WSInfoservice.getPendingTransactionsResponse getPendingTransactions(WSInfoserviceCustomer1.WSInfoservice.getPendingTransactions request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WSInfoserviceCustomer1.WSInfoservice.TechnicalFault), Action="", Name="TechnicalFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSInfoserviceCustomer1.WSInfoservice.getNewTransactionsResponse getNewTransactions(WSInfoserviceCustomer1.WSInfoservice.getNewTransactions request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInvoicingTransactions", WrapperNamespace="http://infoservice.webservice.as24.com/", IsWrapped=true)]
    public partial class getInvoicingTransactions {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infoservice.webservice.as24.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime date;
        
        public getInvoicingTransactions() {
        }
        
        public getInvoicingTransactions(System.DateTime date) {
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInvoicingTransactionsResponse", WrapperNamespace="http://infoservice.webservice.as24.com/", IsWrapped=true)]
    public partial class getInvoicingTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infoservice.webservice.as24.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSInfoserviceCustomer1.WSInfoservice.transaction[] @return;
        
        public getInvoicingTransactionsResponse() {
        }
        
        public getInvoicingTransactionsResponse(WSInfoserviceCustomer1.WSInfoservice.transaction[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPendingTransactions", WrapperNamespace="http://infoservice.webservice.as24.com/", IsWrapped=true)]
    public partial class getPendingTransactions {
        
        public getPendingTransactions() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPendingTransactionsResponse", WrapperNamespace="http://infoservice.webservice.as24.com/", IsWrapped=true)]
    public partial class getPendingTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infoservice.webservice.as24.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSInfoserviceCustomer1.WSInfoservice.transaction[] @return;
        
        public getPendingTransactionsResponse() {
        }
        
        public getPendingTransactionsResponse(WSInfoserviceCustomer1.WSInfoservice.transaction[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNewTransactions", WrapperNamespace="http://infoservice.webservice.as24.com/", IsWrapped=true)]
    public partial class getNewTransactions {
        
        public getNewTransactions() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNewTransactionsResponse", WrapperNamespace="http://infoservice.webservice.as24.com/", IsWrapped=true)]
    public partial class getNewTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infoservice.webservice.as24.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSInfoserviceCustomer1.WSInfoservice.transaction[] @return;
        
        public getNewTransactionsResponse() {
        }
        
        public getNewTransactionsResponse(WSInfoserviceCustomer1.WSInfoservice.transaction[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InfoServiceChannel : WSInfoserviceCustomer1.WSInfoservice.InfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InfoServiceClient : System.ServiceModel.ClientBase<WSInfoserviceCustomer1.WSInfoservice.InfoService>, WSInfoserviceCustomer1.WSInfoservice.InfoService {
        
        public InfoServiceClient() {
        }
        
        public InfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSInfoserviceCustomer1.WSInfoservice.getInvoicingTransactionsResponse WSInfoserviceCustomer1.WSInfoservice.InfoService.getInvoicingTransactions(WSInfoserviceCustomer1.WSInfoservice.getInvoicingTransactions request) {
            return base.Channel.getInvoicingTransactions(request);
        }
        
        public WSInfoserviceCustomer1.WSInfoservice.transaction[] getInvoicingTransactions(System.DateTime date) {
            WSInfoserviceCustomer1.WSInfoservice.getInvoicingTransactions inValue = new WSInfoserviceCustomer1.WSInfoservice.getInvoicingTransactions();
            inValue.date = date;
            WSInfoserviceCustomer1.WSInfoservice.getInvoicingTransactionsResponse retVal = ((WSInfoserviceCustomer1.WSInfoservice.InfoService)(this)).getInvoicingTransactions(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSInfoserviceCustomer1.WSInfoservice.getPendingTransactionsResponse WSInfoserviceCustomer1.WSInfoservice.InfoService.getPendingTransactions(WSInfoserviceCustomer1.WSInfoservice.getPendingTransactions request) {
            return base.Channel.getPendingTransactions(request);
        }
        
        public WSInfoserviceCustomer1.WSInfoservice.transaction[] getPendingTransactions() {
            WSInfoserviceCustomer1.WSInfoservice.getPendingTransactions inValue = new WSInfoserviceCustomer1.WSInfoservice.getPendingTransactions();
            WSInfoserviceCustomer1.WSInfoservice.getPendingTransactionsResponse retVal = ((WSInfoserviceCustomer1.WSInfoservice.InfoService)(this)).getPendingTransactions(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSInfoserviceCustomer1.WSInfoservice.getNewTransactionsResponse WSInfoserviceCustomer1.WSInfoservice.InfoService.getNewTransactions(WSInfoserviceCustomer1.WSInfoservice.getNewTransactions request) {
            return base.Channel.getNewTransactions(request);
        }
        
        public WSInfoserviceCustomer1.WSInfoservice.transaction[] getNewTransactions() {
            WSInfoserviceCustomer1.WSInfoservice.getNewTransactions inValue = new WSInfoserviceCustomer1.WSInfoservice.getNewTransactions();
            WSInfoserviceCustomer1.WSInfoservice.getNewTransactionsResponse retVal = ((WSInfoserviceCustomer1.WSInfoservice.InfoService)(this)).getNewTransactions(inValue);
            return retVal.@return;
        }
    }
}
